# Generated by Django 3.2 on 2021-05-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('slug', models.SlugField(max_length=120, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('fotter', models.TextField(blank=True, default='', verbose_name='fotter')),
                ('keywords', models.TextField(blank=True, default='', verbose_name='keyworks')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
