# Generated by Django 3.2 on 2021-05-03 04:50

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumImageThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='color name')),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='color')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='X', max_length=30, unique=True, verbose_name='size')),
                ('code', models.CharField(default=0, max_length=2, verbose_name='code')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='CatalogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('discount', models.CharField(blank=True, choices=[('', 'ללא הנחה'), ('/static/assets/catalog/imgs/discount_10.gif', '10% הנחה'), ('/static/assets/catalog/imgs/discount_20.gif', '20% הנחה')], default='', max_length=50, null=True)),
                ('colors', models.ManyToManyField(to='catalog.Color')),
                ('sizes', models.ManyToManyField(to='catalog.ProductSize')),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='CatalogAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('slug', models.SlugField(max_length=120, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('fotter', models.TextField(blank=True, default='', verbose_name='fotter')),
                ('keywords', models.TextField(blank=True, default='', verbose_name='keyworks')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('images', models.ManyToManyField(through='catalog.AlbumImageThrough', to='catalog.CatalogImage')),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
        migrations.AddField(
            model_name='albumimagethrough',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalogalbum'),
        ),
        migrations.AddField(
            model_name='albumimagethrough',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalogimage'),
        ),
    ]
