# Generated by Django 3.2 on 2021-05-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogimage',
            name='image',
            field=models.ImageField(upload_to='CatalogImage', verbose_name='image'),
        ),
    ]
