# Generated by Django 3.2 on 2021-05-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210502_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogimage',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='catalogimage',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
